
# backend/agents/validator.py
from .tools import AgentTools, Prediction

# Define acceptable thresholds
MIN_CONFIDENCE_THRESHOLD = 0.60 

class ValidatorAgent:
    """
    An agent that validates the outputs of other agents or tools before they are sent
    to the user. It acts as a safety layer to prevent hallucinations and ensure quality.
    """

    def __init__(self, tool_client: AgentTools):
        """
        Initializes the agent with a client to re-query tools for validation.

        Args:
            tool_client: A class that implements the AgentTools protocol.
        """
        self.tools = tool_client

    def validate_prediction(self, sr_number: str, initial_prediction: Prediction) -> tuple[bool, str]:
        """
        Validates an ETA prediction by re-querying the tool and checking for consistency
        and quality.

        Args:
            sr_number: The service request number.
            initial_prediction: The prediction object generated by the primary agent/tool.

        Returns:
            A tuple containing:
            - bool: True if the prediction is valid, False otherwise.
            - str: A reason for the validation failure, or an empty string if valid.
        """
        print(f"Validator: Validating prediction for {sr_number}")

       
        if initial_prediction['confidence'] < MIN_CONFIDENCE_THRESHOLD:
            reason = f"Confidence ({initial_prediction['confidence']:.0%}) is below threshold ({MIN_CONFIDENCE_THRESHOLD:.0%})."
            print(f"Validation FAILED: {reason}")
            return False, reason

        try:
            validation_prediction = self.tools.predict_eta(sr_number)
        except Exception as e:
            reason = f"Failed to re-query prediction tool for validation: {e}"
            print(f"Validation FAILED: {reason}")
            return False, reason

        # Compare key fields. For dates/numbers, allow a small tolerance.
        if initial_prediction['eta_date'] != validation_prediction['eta_date']:
            reason = f"ETA date mismatch during validation: {initial_prediction['eta_date']} vs {validation_prediction['eta_date']}."
            print(f"Validation FAILED: {reason}")
            return False, reason

        print(f"Validation PASSED for {sr_number}")
        return True, ""

